
/* autogenerated from audio_orc_int_bias.orc */

/* audio_orc_int_bias */
.global audio_orc_int_bias
.p2align 4
audio_orc_int_bias:
# LOOP SHIFT 0
# LOOP SHIFT 1
# LOOP SHIFT 2
# LOOP SHIFT 3
# LOOP SHIFT 4
# LOOP SHIFT 5
# LOOP SHIFT 5
# LOOP SHIFT 4
# LOOP SHIFT 3
# LOOP SHIFT 2
# LOOP SHIFT 1
# LOOP SHIFT 0
  endbr64 
  mov $32, %eax
  sub 24(%rdi), %eax
  and $127, %eax
  sar $2, %eax
  cmp %eax, 8(%rdi)
  jle 6f
  movl %eax, 12(%rdi)
  movl 8(%rdi), %ecx
  sub %eax, %ecx
  mov %ecx, %eax
  sar $6, %ecx
  movl %ecx, 16(%rdi)
  and $63, %eax
  movl %eax, 20(%rdi)
  jmp 7f
6:
  movl 8(%rdi), %eax
  movl %eax, 12(%rdi)
  mov $0, %eax
  movl %eax, 16(%rdi)
  movl %eax, 20(%rdi)
7:
  mov 24(%rdi), %rax
  mov 56(%rdi), %rdx
  testl $1, 12(%rdi)
  jz 16f
16:
  testl $2, 12(%rdi)
  jz 17f
17:
  testl $4, 12(%rdi)
  jz 18f
18:
  testl $8, 12(%rdi)
  jz 19f
19:
  testl $16, 12(%rdi)
  jz 20f
20:
1:
  cmpb $0, 16(%rdi)
  jz 3f
  movl 16(%rdi), %esi
.p2align 4
2:
  add $-1, %esi
  jnz 2b
3:
  testl $32, 20(%rdi)
  jz 13f
13:
  testl $16, 20(%rdi)
  jz 12f
12:
  testl $8, 20(%rdi)
  jz 11f
11:
  testl $4, 20(%rdi)
  jz 10f
10:
  testl $2, 20(%rdi)
  jz 9f
9:
  testl $1, 20(%rdi)
  jz 8f
8:
  vzeroupper 
  retq 


