
/* autogenerated from audiomixer_orc_add_s32.orc */

/* audiomixer_orc_add_s32 */
.global audiomixer_orc_add_s32
.p2align 4
audiomixer_orc_add_s32:
# LOOP SHIFT 0
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 1
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 2
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 3
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 3
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 2
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 1
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
# LOOP SHIFT 0
# 0: loadl
# 1: loadl
# 2: addssl
# loading constant 18446744073709551615 0xffffffffffffffff
# loading constant 2147483647 0x        7fffffff
# 3: storel
  endbr64 
  mov $32, %eax
  sub 24(%rdi), %eax
  and $31, %eax
  sar $2, %eax
  cmp %eax, 8(%rdi)
  jle 6f
  movl %eax, 12(%rdi)
  movl 8(%rdi), %ecx
  sub %eax, %ecx
  mov %ecx, %eax
  sar $4, %ecx
  movl %ecx, 16(%rdi)
  and $15, %eax
  movl %eax, 20(%rdi)
  jmp 7f
6:
  movl 8(%rdi), %eax
  movl %eax, 12(%rdi)
  mov $0, %eax
  movl %eax, 16(%rdi)
  movl %eax, 20(%rdi)
7:
  mov 24(%rdi), %rax
  mov 56(%rdi), %rdx
  testl $1, 12(%rdi)
  jz 16f
  vmovd 0(%rax), %xmm0
  vmovd 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovd %xmm0, 0(%rax)
  leaq 4(%rax), %rax
  leaq 4(%rdx), %rdx
16:
  testl $2, 12(%rdi)
  jz 17f
  vmovq 0(%rax), %xmm0
  vmovq 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovq %xmm0, 0(%rax)
  leaq 8(%rax), %rax
  leaq 8(%rdx), %rdx
17:
  testl $4, 12(%rdi)
  jz 18f
  vmovdqu 0(%rax), %xmm0
  vmovdqu 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovdqu %xmm0, 0(%rax)
  leaq 16(%rax), %rax
  leaq 16(%rdx), %rdx
18:
1:
  cmpb $0, 16(%rdi)
  jz 3f
  movl 16(%rdi), %esi
.p2align 4
2:
  vmovdqa 0(%rax), %ymm0
  vmovdqu 0(%rdx), %ymm1
  vmovdqa %ymm0, %ymm2
  vmovdqa %ymm0, %ymm3
  vpxor %ymm1, %ymm0, %ymm2
  vpaddd %ymm1, %ymm0, %ymm0
  vpxor %ymm0, %ymm3, %ymm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %ymm4, %ymm3, %ymm3
  vpor %ymm3, %ymm2, %ymm2
  vpsrad $31, %ymm2, %ymm2
  vpsrad $31, %ymm1, %ymm3
  vpand %ymm2, %ymm0, %ymm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %ymm5, %ymm3, %ymm3
  vpandn %ymm3, %ymm2, %ymm2
  vpor %ymm2, %ymm0, %ymm0
  vmovdqa %ymm0, 0(%rax)
  vmovdqa 32(%rax), %ymm0
  vmovdqu 32(%rdx), %ymm1
  vmovdqa %ymm0, %ymm2
  vmovdqa %ymm0, %ymm3
  vpxor %ymm1, %ymm0, %ymm2
  vpaddd %ymm1, %ymm0, %ymm0
  vpxor %ymm0, %ymm3, %ymm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %ymm4, %ymm3, %ymm3
  vpor %ymm3, %ymm2, %ymm2
  vpsrad $31, %ymm2, %ymm2
  vpsrad $31, %ymm1, %ymm3
  vpand %ymm2, %ymm0, %ymm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %ymm5, %ymm3, %ymm3
  vpandn %ymm3, %ymm2, %ymm2
  vpor %ymm2, %ymm0, %ymm0
  vmovdqa %ymm0, 32(%rax)
  leaq 64(%rax), %rax
  leaq 64(%rdx), %rdx
  add $-1, %esi
  jnz 2b
3:
  testl $8, 20(%rdi)
  jz 11f
  vmovdqu 0(%rax), %ymm0
  vmovdqu 0(%rdx), %ymm1
  vmovdqa %ymm0, %ymm2
  vmovdqa %ymm0, %ymm3
  vpxor %ymm1, %ymm0, %ymm2
  vpaddd %ymm1, %ymm0, %ymm0
  vpxor %ymm0, %ymm3, %ymm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %ymm4, %ymm3, %ymm3
  vpor %ymm3, %ymm2, %ymm2
  vpsrad $31, %ymm2, %ymm2
  vpsrad $31, %ymm1, %ymm3
  vpand %ymm2, %ymm0, %ymm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %ymm5, %ymm3, %ymm3
  vpandn %ymm3, %ymm2, %ymm2
  vpor %ymm2, %ymm0, %ymm0
  vmovdqu %ymm0, 0(%rax)
  leaq 32(%rax), %rax
  leaq 32(%rdx), %rdx
11:
  testl $4, 20(%rdi)
  jz 10f
  vmovdqu 0(%rax), %xmm0
  vmovdqu 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovdqu %xmm0, 0(%rax)
  leaq 16(%rax), %rax
  leaq 16(%rdx), %rdx
10:
  testl $2, 20(%rdi)
  jz 9f
  vmovq 0(%rax), %xmm0
  vmovq 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovq %xmm0, 0(%rax)
  leaq 8(%rax), %rax
  leaq 8(%rdx), %rdx
9:
  testl $1, 20(%rdi)
  jz 8f
  vmovd 0(%rax), %xmm0
  vmovd 0(%rdx), %xmm1
  vmovdqa %xmm0, %xmm2
  vmovdqa %xmm0, %xmm3
  vpxor %xmm1, %xmm0, %xmm2
  vpaddd %xmm1, %xmm0, %xmm0
  vpxor %xmm0, %xmm3, %xmm3
  mov $-1, %ecx
  vmovd %ecx, %xmm4
  vpbroadcastd %xmm4, %ymm4
  vpxor %xmm4, %xmm3, %xmm3
  vpor %xmm3, %xmm2, %xmm2
  vpsrad $31, %xmm2, %xmm2
  vpsrad $31, %xmm1, %xmm3
  vpand %xmm2, %xmm0, %xmm0
  vpcmpeqb %ymm5, %ymm5, %ymm5
  vpsrld $1, %ymm5, %ymm5
  vpxor %xmm5, %xmm3, %xmm3
  vpandn %xmm3, %xmm2, %xmm2
  vpor %xmm2, %xmm0, %xmm0
  vmovd %xmm0, 0(%rax)
  leaq 4(%rax), %rax
  leaq 4(%rdx), %rdx
8:
  vzeroupper 
  retq 


